---
- hosts: localhost
  become: yes
  name: install_jenkins 
  tasks:
    - name: Creating Directory For Jenkins!
      file: state=directory path=/etc/yum.repos.d/jenkins.repo
    - name: Downloading Sources
      get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key dest=/etc/yum.repos.d/jenkins.repo
    - name: Getting RPM Key
      rpm_key:
        state: present
        key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    - name: Finally Installing Jenkins! 
      yum:
        name: jenkins 
        state: latest